---
version: 2
updates:

    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
      groups:
          - name: actions
            patterns:
                - '*'

    - package-ecosystem: pre-commit
      directory: /
      schedule:
          interval: weekly
      groups:
          - name: pre-commit
            patterns:
                - '*'
