#ifndef STATS_H
#define STATS_H

#include <cstddef>

#include "constants.h"

namespace stats {
// number of ion stats counters that should be divided by the ion populations
constexpr int nstatcounters_ratecoeff = 18;

// global statistics (all cells combined)
enum eventcounters {
  COUNTER_MA_STAT_ACTIVATION_COLLEXC = 0,
  COUNTER_MA_STAT_ACTIVATION_COLLION = 1,
  COUNTER_MA_STAT_ACTIVATION_NTCOLLEXC = 2,
  COUNTER_MA_STAT_ACTIVATION_NTCOLLION = 3,
  COUNTER_MA_STAT_ACTIVATION_BB = 4,
  COUNTER_MA_STAT_ACTIVATION_BF = 5,
  COUNTER_MA_STAT_ACTIVATION_FB = 6,
  COUNTER_MA_STAT_DEACTIVATION_COLLDEEXC = 7,
  COUNTER_MA_STAT_DEACTIVATION_COLLRECOMB = 8,
  COUNTER_MA_STAT_DEACTIVATION_BB = 9,
  COUNTER_MA_STAT_DEACTIVATION_FB = 10,
  COUNTER_MA_STAT_INTERNALUPHIGHER = 11,
  COUNTER_MA_STAT_INTERNALUPHIGHERNT = 12,
  COUNTER_MA_STAT_INTERNALDOWNLOWER = 13,
  COUNTER_K_STAT_TO_MA_COLLEXC = 14,
  COUNTER_K_STAT_TO_MA_COLLION = 15,
  COUNTER_K_STAT_TO_R_FF = 16,
  COUNTER_K_STAT_TO_R_FB = 17,
  COUNTER_K_STAT_TO_R_BB = 18,
  COUNTER_K_STAT_FROM_FF = 19,
  COUNTER_K_STAT_FROM_BF = 20,
  COUNTER_NT_STAT_FROM_GAMMA = 21,
  COUNTER_NT_STAT_TO_ionisation = 22,
  COUNTER_NT_STAT_TO_EXCITATION = 23,
  COUNTER_NT_STAT_TO_KPKT = 24,
  COUNTER_K_STAT_FROM_EARLIERDECAY = 25,
  COUNTER_INTERACTIONS = 26,
  COUNTER_ESCOUNTER = 27,
  COUNTER_RESONANCESCATTERINGS = 28,
  COUNTER_CELLCROSSINGS = 29,
  COUNTER_UPSCATTER = 30,
  COUNTER_DOWNSCATTER = 31,
  COUNTER_UPDATECELL = 32,
  COUNTER_COUNT = 33,
};

DEVICE_FUNC void increment(enum eventcounters i);

void pkt_action_counters_reset();

[[nodiscard]] auto get_counter(enum eventcounters i) -> ptrdiff_t;

void pkt_action_counters_printout(int nts);

}  // namespace stats

#endif  // STATS_H
