---
name: Compile and lint
permissions:
  contents: read
on:
    push:
        branches-ignore:
            - classic*
    workflow_dispatch:

jobs:
    clang-tidy-cppcheck:
        name: Format and lint
        runs-on: macos-26
        steps:
            - uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6

            - uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: 'latest-stable'

            - name: Install dependencies
              run: |
                  brew update
                  brew install llvm
                  echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH

                  echo "LDFLAGS=-L/opt/homebrew/opt/llvm/lib" >> $GITHUB_ENV
                  echo "CPPFLAGS=-I/opt/homebrew/opt/llvm/include" >> $GITHUB_ENV

                  echo "CXXFLAGS=-I/opt/homebrew/opt/libomp/include" >> $GITHUB_ENV

                  echo "LIBRARY_PATH=/opt/homebrew/opt/lib" >> $GITHUB_ENV
                  echo "LD_LIBRARY_PATH=/opt/homebrew/opt/lib" >> $GITHUB_ENV
                  echo "CPATH=$HOMEBREW_PREFIX/include:$CPATH" >> $GITHUB_ENV

                  brew install openmpi gsl cppcheck || true
                  python3 -m pip install compiledb

            - name: Generate compile_commands.json
              run: |
                  cp artisoptions_nltenebular.h artisoptions.h
                  make clean
                  python3 -m compiledb -n --full-path make TESTMODE=ON

            - name: Run pre-commit hooks
              uses: j178/prek-action@v2

            - name: Run clang-tidy
              run: |
                  clang-tidy --version
                  xcrun run-clang-tidy

            - name: Run cppcheck
              run: |
                  cppcheck --version
                  cppcheck --force --error-exitcode=1 --language=c++ -i third_party --enable=all --inconclusive --inline-suppr --suppress=knownConditionTrueFalse --suppress=redundantAssignment --suppress=knownArgument --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=useStlAlgorithm --check-level=exhaustive .

    compile:
        strategy:
            matrix:
                compiler:
                    [
                        {name: gcc, ver: 14},
                        {name: gcc, ver: 15},
                        {name: clang, ver: 22},
                    ]
            fail-fast: false

        runs-on: ubuntu-24.04
        name: Ubuntu ${{ matrix.compiler.name }} ${{ matrix.compiler.ver }}
        steps:
            - uses: actions/checkout@v6

            - name: Get CPU Core count for parallel builds
              id: cpu-count
              run: |
                  echo "CPU count: $(nproc --all)"
                  echo "count=$(nproc --all)" >> $GITHUB_OUTPUT

            # - name: Install ${{ matrix.compiler.name }} ${{ matrix.compiler.ver }}
            #   if: matrix.compiler.name == 'gcc' && matrix.compiler.ver == 15
            #   uses: fortran-lang/setup-fortran@v1.9.0
            #   with:
            #       compiler: ${{ matrix.compiler.name }}
            #       version: ${{ matrix.compiler.ver }}

            - name: Install ${{ matrix.compiler.name }} ${{ matrix.compiler.ver }}
              if: matrix.compiler.name == 'gcc' && matrix.compiler.ver == 15
              run: |
                  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
                  echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
                  brew install --force gcc@${{ matrix.compiler.ver }}
                    # Add brew binutils to PATH (gcc-15+ requires newer assembler)
                  brew install --force binutils
                  binutils_dir=$(brew --prefix binutils)/bin
                  echo "$binutils_dir" >> $GITHUB_PATH
                  bindir=$(brew --prefix)/bin
                  sudo update-alternatives \
                        --install /usr/bin/gcc gcc ${bindir}/gcc-${{ matrix.compiler.ver }} 100 \
                        --slave /usr/bin/gfortran gfortran ${bindir}/gfortran-${{ matrix.compiler.ver }} \
                        --slave /usr/bin/gcov gcov ${bindir}/gcov-${{ matrix.compiler.ver }} \
                        --slave /usr/bin/g++ g++ ${bindir}/g++-${{ matrix.compiler.ver }}

            - name: Select GCC version as default C++ compiler
              if: matrix.compiler.name == 'gcc'
              run: |
                  echo "CXX=g++-${{ matrix.compiler.ver }}" >> $GITHUB_ENV
                  echo "OMPI_CXX=g++-${{ matrix.compiler.ver }}" >> $GITHUB_ENV

            - name: Install Clang ${{ matrix.compiler.ver }}
              if: matrix.compiler.name == 'clang'
              run: |
                  wget https://apt.llvm.org/llvm.sh
                  chmod +x llvm.sh
                  sudo ./llvm.sh ${{ matrix.compiler.ver }}
                  sudo apt-get install -y lld-${{ matrix.compiler.ver }} clang-${{ matrix.compiler.ver }} libomp-${{ matrix.compiler.ver }}-dev
                  echo "CXX=clang++-${{ matrix.compiler.ver }}" >> $GITHUB_ENV
                  echo "OMPI_CXX=clang++-${{ matrix.compiler.ver }}" >> $GITHUB_ENV
                  echo "LDFLAGS=-L/usr/lib/llvm-${{ matrix.compiler.ver }}/lib" >> $GITHUB_ENV

            - name: Install GSL
              run: |
                  sudo apt-get update
                  sudo apt install -y libgsl-dev

            - name: Install TBB
              if: matrix.compiler.name == 'gcc'
              run: |
                  sudo apt install libtbb-dev

            - name: Install Open MPI
              run: |
                  sudo apt install -y openmpi-bin libopenmpi-dev

            - name: Compile classic mode
              run: |
                  cp -v -p artisoptions_classic.h artisoptions.h
                  make clean
                  make -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Compile classic mode OPENMP=ON
              run: |
                  make clean
                  make OPENMP=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Compile classic mode STDPAR=ON
              run: |
                  cp -v -p artisoptions_classic.h artisoptions.h
                  make clean
                  make STDPAR=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Compile nebular mode
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Compile nebular mode EIGEN=OFF
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make -j${{ steps.cpu-count.outputs.count}} EIGEN=OFF sn3d exspec

            - name: Compile nebular mode OPENMP=ON
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make OPENMP=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Compile nebular mode STDPAR=ON
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make STDPAR=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Compile all remaining option files
              run: |
                  for file in $(find . -name "artisoptions_*.h" ! -name "artisoptions_classic.h" ! -name "artisoptions_nltenebular.h"); do
                      cp -v -p "$file" artisoptions.h
                      make sn3d
                  done

    mac-clang:
        runs-on: macos-26
        name: Apple Clang and LLVM Clang
        steps:
            - uses: actions/checkout@v6

            - name: Get CPU Core count for parallel builds
              id: cpu-count
              run: |
                  echo "CPU count: $(nproc --all)"
                  echo "count=$(nproc --all)" >> $GITHUB_OUTPUT

            - uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: 'latest-stable'

            - name: Install Open MPI
              run: |
                  brew update
                  brew install openmpi || true

            - name: Install OpenMP
              run: |
                  brew install libomp || true
                  brew link --force libomp

                  echo "LDFLAGS=-L/opt/homebrew/opt/libomp/lib $LDFLAGS" >> $GITHUB_ENV
                  echo "CXXFLAGS=-I/opt/homebrew/opt/libomp/include $CXXFLAGS" >> $GITHUB_ENV

            - name: Apple Clang Compile classic mode
              run: |
                  cp -v -p artisoptions_classic.h artisoptions.h
                  make clean
                  make -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Apple Clang Compile classic mode OPENMP=ON
              run: |
                  make clean
                  make OPENMP=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Apple Clang Compile classic mode STDPAR=ON
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make STDPAR=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Apple Clang Compile nebular mode
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Apple Clang Compile nebular mode OPENMP=ON
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make OPENMP=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Apple Clang Compile nebular mode STDPAR=ON
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make STDPAR=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Apple Clang Compile all remaining option files
              run: |
                  for file in $(find . -name "artisoptions_*.h" ! -name "artisoptions_classic.h" ! -name "artisoptions_nltenebular.h"); do
                      cp -v -p "$file" artisoptions.h
                      make sn3d
                  done

            - name: Install LLVM
              run: |
                  brew install llvm || true
                  echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
                  echo "LDFLAGS=-L/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/llvm/lib/c++ -L/opt/homebrew/opt/llvm/lib/unwind -lunwind" >> $GITHUB_ENV
                  echo "CPPFLAGS=-I/opt/homebrew/opt/llvm/include" >> $GITHUB_ENV
                  echo "CXX=clang++" >> $GITHUB_ENV

            - name: LLVM Clang Compile classic mode
              run: |
                  cp -v -p artisoptions_classic.h artisoptions.h
                  make clean
                  make -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: LLVM Clang Compile classic mode OPENMP=ON
              run: |
                  make clean
                  make OPENMP=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: LLVM Clang Compile classic mode STDPAR=ON
              run: |
                  clang++ -v
                  cp -v -p artisoptions_classic.h artisoptions.h
                  make clean
                  make STDPAR=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: LLVM Clang Compile nebular mode
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: LLVM Clang Compile nebular mode OPENMP=ON
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make OPENMP=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: LLVM Clang Compile nebular mode STDPAR=ON
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make STDPAR=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: LLVM Clang Compile all remaining option files
              run: |
                  for file in $(find . -name "artisoptions_*.h" ! -name "artisoptions_classic.h" ! -name "artisoptions_nltenebular.h"); do
                      cp -v -p "$file" artisoptions.h
                      make sn3d
                  done

    amd-rocm-hipcc:
        runs-on: ubuntu-24.04
        name: AMD ROCm hipcc
        container:
            image: rocm/dev-ubuntu-24.04:7.2-complete
        steps:
            - name: Get CPU Core count for parallel builds
              id: cpu-count
              run: |
                  echo "CPU count: $(nproc --all)"
                  echo "count=$(nproc --all)" >> $GITHUB_OUTPUT

            - name: Set MPI compiler to hipcc
              run: |
                  hipcc --version
                  hipconfig
                  echo "CXX=hipcc" >> $GITHUB_ENV
                  echo "OMPI_CXX=hipcc" >> $GITHUB_ENV
                  echo "ROCM_PATH=$(hipconfig --rocmpath)" >> $GITHUB_ENV

            - name: Install Open MPI and git
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libopenmpi-dev openmpi-bin
                  sudo apt-get install -y git
                  git config --global --add safe.directory /__w/artis/artis

            - uses: actions/checkout@v6
              with:
                    fetch-depth: 0

            - name: Compile classic mode STDPAR=ON GPU=ON
              run: |
                  cp -v -p artisoptions_classic.h artisoptions.h
                  make clean
                  make STDPAR=ON GPU=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Compile nebular mode STDPAR=ON GPU=ON
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make STDPAR=ON GPU=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Compile nebular mode
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make -j${{ steps.cpu-count.outputs.count}} sn3d exspec

    nvidia-nvhpc:
        name: NVIDIA NVHPC nvc++
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6

            - name: Get CPU Core count for parallel builds
              id: cpu-count
              run: |
                  echo "CPU count: $(nproc --all)"
                  echo "count=$(nproc --all)" >> $GITHUB_OUTPUT

            - name: Install nvc++
              uses: fortran-lang/setup-fortran@v1.9.0
              with:
                  compiler: nvidia-hpc
                  version: 26.1

            - name: Set nvc++ as compiler
              run: |
                  echo "CXX=nvc++" >> $GITHUB_ENV
                  echo "OMPI_CXX=nvc++" >> $GITHUB_ENV

            - name: Install Open MPI
              run: |
                  sudo apt install -y openmpi-bin libopenmpi-dev

            - name: Compile classic mode STDPAR=ON GPU=ON
              run: |
                  cp -v -p artisoptions_classic.h artisoptions.h
                  make clean
                  make STDPAR=ON GPU=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Compile nebular mode STDPAR=ON GPU=ON
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make STDPAR=ON GPU=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Compile nebular mode STDPAR=ON
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make STDPAR=ON -j${{ steps.cpu-count.outputs.count}} sn3d exspec

            - name: Compile nebular mode
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
                  make clean
                  make -j${{ steps.cpu-count.outputs.count}} sn3d exspec
