---
name: CI Extensive Test Mode
permissions:
  contents: read
on:
    push:
        branches-ignore:
            - classic*
    workflow_dispatch:

concurrency:
  # Use github.run_id on main or develop branch (unlimited concurrency)
  # Use github.ref otherwise, so that it's unique per branch or PR
  group: ${{ github.workflow }}-${{ github.ref_name == 'develop' && github.run_id || github.ref }}
  cancel-in-progress: false

jobs:
    showconcurrencygroupname:
        name: Show concurrency group name
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Concurrency group: ${{ github.workflow }}-${{ github.ref_name == 'develop' && github.run_id || github.ref }}"

    citestmode:
        name: testmode ON
        uses: ./.github/workflows/ci.yml
        with:
            testmode: ON
        secrets: inherit
