---
name: CI Extensive Test Mode
permissions:
  contents: read
on:
    push:
        branches-ignore:
            - classic*
    workflow_dispatch:

concurrency:
  # unlimited concurrency on main branch ()
  # Otherwise use the ref name (branch or tag) as concurrency group, so that only one workflow runs per branch or tag at a time
  group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.run_id || github.ref }}
  cancel-in-progress: false

jobs:
    showconcurrencygroupname:
        name: Show concurrency group name
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Concurrency group: ${{ github.workflow }}-${{ github.ref_name == 'main' && github.run_id || github.ref }}"

    citestmode:
        name: testmode ON
        uses: ./.github/workflows/ci.yml
        with:
            testmode: ON
        secrets: inherit
