---
name: CI Slow

on:
    push:
        branches:
            - main
            - develop
    workflow_dispatch:
    pull_request:

jobs:
    citestmode:
        name: testmode ON
        uses: ./.github/workflows/ci.yml
        with:
            testmode: ON
        secrets: inherit
