---
name: CI Extensive Test Mode

on:
    push:
        branches-ignore:
            - classic*
    workflow_dispatch:

concurrency:
  # Use github.run_id on main or develop branch (unlimited concurrency)
  # Use github.ref otherwise, so that it's unique per branch or PR
  group: ${{ github.workflow }}-${{ github.ref_protected && github.run_id || github.ref }}
  cancel-in-progress: false

jobs:
    citestmode:
        name: testmode ON
        uses: ./.github/workflows/ci.yml
        with:
            testmode: ON
        secrets: inherit
