name: "Copilot Setup Steps"

on:
    workflow_dispatch:
    push:
        paths:
            - .github/workflows/copilot-setup-steps.yml
    pull_request:
        paths:
            - .github/workflows/copilot-setup-steps.yml

jobs:
    copilot-setup-steps:
        runs-on: ubuntu-26.04

        permissions:
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Set gcc-14 as default compiler
              run: |
                  echo "CXX=g++-14" >> $GITHUB_ENV
                  echo "OMPI_CXX=g++-14" >> $GITHUB_ENV

            - name: Install Open MPI and TBB
              run: |
                  sudo apt-get update
                  sudo apt-get install -y --no-install-recommends openmpi-bin libopenmpi-dev libtbb-dev

            - name: Set artisoptions to nltenebular
              run: |
                  cp -v -p artisoptions_nltenebular.h artisoptions.h
